name: wakelock_service
description: Wakelock Service
version: 1.1.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: "3.19.0"

dependencies:
  flutter:
    sdk: flutter
  wakelock_plus: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
